### ISSUE TITLE
Combine Off/On and Enable/Disable command to Two Toggle command

### ISSUE THREAD

**Issue by LintaoAmons** [miversen33/sunglasses.nvim#10]

**Comment by miversen33** [comment]
I will not be removing `SunglassesOff`/`SunglassesOn`, or `SunglassesEnable`/`SunglassesDisable`.

The ability to manually set or remove sunglasses (both temporarily and permanently) should be exposed and not be something that you have to toggle and guess at.

That said, I am not against an On/Off and Enable/Disable set of toggle commands. I don't know what they would be called, but conceivably there would need to be 3 different toggle commands

- `SunglassesOff`/`SunglassesOn` (This could probably have `SunglassesToggle`)
- `SunglassesEnable`/`SunglassesDisable` (I don't know what name fits this toggle command...?)
- `SunglassesPause`/`SunglassesResume` (I have no idea what this toggle command would be either).

These 3 are different enough that I would want them to have their own toggle commands (if this was something that would need to be done).

Alternatively, there are a few ways you could check to see if a window is shaded yourself with the underlying (not yet documented) api.

1) Check if there is a window variable on the window called `Sunglasses` and check if its true
```lua
if vim.api.nvim_win_get_var(vim.api.nvim_get_current_win(), 'Sunglasses')) == true then
-- Sunglasses is enabled on this window
end
```

2) Ask sunglasses if the window is shaded
```lua
local window = require("sunglasses.window").get(-1)
if window and window:is_shaded() then
-- Sunglasses is enabled on this window
end
```

Both of these need to be documented yet, I just haven't gotten around to doing them. Alternatively if you don't wan to do that, come up with fitting names for the other 2 toggle targets and I am open to implementing 3 toggle commands :)

**Comment by agaro1121** [comment]
Exposing the `Window.global_disabled` would make it very easy to create a toggle for Enable/Disable

**Comment by miversen33** [comment]
I kinda forgot this issue existed lol. Anyway I just added [`:SunglassesToggle`](https://github.com/miversen33/sunglasses.nvim#sunglassestoggle). Since OP did not reply, I am closing this out as "complete" with this push.

**Comment by LintaoAmons** [comment]
Oh, thanks, I also forgot this one..

Now I'm using this plugin every day, and this would be very helpful when I open/close a diff view tab
