### ISSUE TITLE
How to disable the plugin by default, only start when required

### ISSUE THREAD

**Issue by LintaoAmons** [miversen33/sunglasses.nvim#13]
![image](https://github.com/miversen33/sunglasses.nvim/assets/95092244/22f6b124-a712-448f-ab05-41805b648007)

Here's my current config, but it will start the sunglasses when I enter nvim.

So I actually want it do not take effect at the very beginning.

**Comment by miversen33** [comment]
There isn't a "built in way" to accomplish this. You could just disable it immediately after setup though

```lua
{
    {
        "miversen33/sunglasses.nvim",
        config = function()
            local sunglasses_options = {
                filter_percent = 0.65,
                filter_type = "NOSYNTAX"
            },

            require("sunglasses").setup(sunglasses_options)
            vim.cmd(':SunglassesDisable')
        end
    }
}
```

Would that work? If not, I would be open to a PR adding some way of preventing the auto disabling of sunglasses :)

**Comment by LintaoAmons** [comment]
Thanks, yes, it works~
