### ISSUE TITLE
[bug] Sunglasses stay on when closing a tab

### ISSUE THREAD

**Issue by davkk** [miversen33/sunglasses.nvim#14]
Hi, 
I have found an issue regarding closing a tab: when I have 2 tabs open and close one of them, the sunglasses stay on for the buffers inside the remaining tab.

Thank you for the cool plugin!

**Comment by miversen33** [comment]
I don't play with tabs too much so while I understand the words you are saying, I don't know that I fully understand what is happening. Think you could record the issue in a gif or mp4 and upload it to the issue for me?

**Comment by miversen33** [comment]
I'm unassigning myself from this. I am going to close this out in a couple weeks if I don't get any sort of update on the question asked.

**Comment by miversen33** [comment]
If this is still an issue, please provide the requested information. For now, closing out
