### ISSUE TITLE
All windows gets dimmed when closing a tab

### ISSUE THREAD

**Issue by yujinyuz** [miversen33/sunglasses.nvim#17]
When I open a file and have 2 splits, disabling syntax works properly when changing to different files.

But if I create a new tab and then close it, both files become dim.

Here's a video to better explain the bug.

https://github.com/miversen33/sunglasses.nvim/assets/10972027/b88d2edc-3445-4a9b-9b97-7264d8514a25

**Comment by miversen33** [comment]
I think I know what is happening here. This is likely related to how sunglasses captures "focus" events. Sunglasses Tracks the `WinEnter`, `BufEnter` and `WinLeave` events. I didn't even think about adding tracking for Tabs. There is also a `TabEnter` and `TabLeave` that I likely need to track as well. I will see about getting a new branch put together adding those. There is likely some logic that needs to be modified as well to handle the "enter" event properly with TabLeave

**Comment by miversen33** [comment]
As a workaround, you should be able to trigger a `BufEnter` event by simply entering either of the buffers you already have open. A `:b .luarc.json` command would likely trigger the appropriate code and get sunglasses back functioning. Alternatively you can probably use the `SunglassesResume` command to force it to unshade the current buffer

**Comment by yujinyuz** [comment]
@miversen33 Thanks.

Focusing and unfocusing on a buffer fixes the issue.

---

I'm just curious. Why not use something like FocusGained and FocusLost for this?

**Comment by miversen33** [comment]
IIRC I tried FocusGained/FocusLost but didn't work.

The wording in the help doc eludes to this being related to the entire program gaining or losing focus as opposed to Focus changing _within_ nvim

```vim
FocusGained                 Nvim got focus.

FocusLost                   Nvim lost focus.  Also (potentially) when
                            a GUI dialog pops up.
```
