### ISSUE TITLE
Neovim 0.9.4 is not currently supported (missing nvim_get_hl_ns)

### ISSUE THREAD

**Issue by newgoliath** [miversen33/sunglasses.nvim#5]
Any thoughts on why it's failing on WinLeave?

```
Error detected while processing WinLeave Autocommands for "*":
Error executing lua callback: ...hare/nvim/lazy/sunglasses.nvim/lua/sunglasses/window.lua:95: attempt to call field 'nvim_get_hl_ns' (a nil v
alue)
stack traceback:
        ...hare/nvim/lazy/sunglasses.nvim/lua/sunglasses/window.lua:95: in function 'is_shaded'
        ...hare/nvim/lazy/sunglasses.nvim/lua/sunglasses/window.lua:142: in function 'can_shade'
        ...hare/nvim/lazy/sunglasses.nvim/lua/sunglasses/window.lua:261: in function <...hare/nvim/lazy/sunglasses.nvim/lua/sunglasses/window
.lua:250>
```

```
:version
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.9.4/share/nvim"

Run :checkhealth for more info
```

**Comment by miversen33** [comment]
Very weird! I will check into this after work :) It should work on 0.9.0 and newer.

For giggles, can you update your log level to `TRACE3` and grab your log for me?

https://github.com/miversen33/sunglasses.nvim#configlog_level

**Comment by miversen33** [comment]
Ahh so it looks like `nvim_set_hl_ns` was added a while ago but `nvim_get_hl_ns` was only recently added

https://github.com/neovim/neovim/issues/24309

I will have to come up with a workaround for stable

**Comment by miversen33** [comment]
@newgoliath I have added a branch [5-nvim_get_ls_ns](https://github.com/miversen33/sunglasses.nvim/tree/5-nvim_get_ls_ns) that should resolve this. I have tested it on neovim 0.9.0 and it appears to be functional.

One side note, there is some weird bug in 0.9.0 that is causing the highlight refreshing logic to bug out. I can't figure out why but for the time being I have disabled the auto highlight refreshing on any neovim version within then 0.9 range.

Lemme know if this fixes your issue

**Comment by LintaoAmons** [comment]
Same issue~

**Comment by miversen33** [comment]
@LintaoAmons can you try the above listed branch?

**Comment by blackheaven** [comment]
it works on the branch

**Comment by miversen33** [comment]
Perfect. @blackheaven @newgoliath @LintaoAmons I have merged this branch into main and removed the branch. This issue is now closed out. I have not updated the version tag yet (I will do that later this afternoon).

Thank you for your help and for reporting this :)
