### ISSUE TITLE
NOSYNTAX filter_type should dim the font color

### ISSUE THREAD

**Issue by LintaoAmons** [miversen33/sunglasses.nvim#9]
![image](https://github.com/miversen33/sunglasses.nvim/assets/95092244/34f40762-15c0-42fc-a371-8878b63fb754)

**Comment by miversen33** [comment]
Nosyntax does dim the font color. It sets the font foreground to either white or black (based on if the background is dark or not) and then applys the shade against the color, shading by the filter_percent.

If you increase your filter_percent, does that make further dim the shade?

If you check the readme, you can see that the screenshots of nosyntax look exactly how you expect

https://github.com/miversen33/sunglasses.nvim#nosyntax

**Comment by LintaoAmons** [comment]
Thx! that's exactly what I want
